### ISSUE TITLE
How to deploy with Binder and voilà, and GitHub pages?

### ISSUE THREAD

**Issue by sbonaretti** [danielfrg/jupyter-flex#24]
Hi!
Thanks so much for this fantastic package! I have just created my very first [dashboard](https://github.com/sbonaretti/Hunter_viz_2020/blob/master/open_literature_flex.ipynb), and I am excited I used jupyter-flex for it as it is super easy and elegant!

Locally everything works like a charm, but I have difficulties at deploying the dashboard:
- On Binder:
  - I have created the repository with binder, and then I have launched Voilà (button in the top bar). The only rendering I get is the text of the notebook. Am I missing some file or some commands that tells Voilà to use jupyter-flex?
- On GitHub pages:
  - Is there a way to deploy the dashboard using GitHub pages?

Looking forward!

**Comment by danielfrg** [comment]
Hi Serena,

You are probably not telling Voila to use the Flex theme so its instead is using the default Voila theme.
You can change this for the binder deployment using `conf.json`.
For example look the one on this repo: `https://github.com/danielfrg/jupyter-flex/blob/master/conf.json`.

You cannot deploy a voila dashboard to GitHub pages since it requires a live kernel to do any computation and Github pages are just static ones.

I am going to close as there is not an actual issue but feel free to ask other questions here or in other tickets.

**Comment by sbonaretti** [comment]
Hi Daniel,
Thanks a lot! I have added the conf.json file to my GitHub repository, launched the repo in binder, and pressed the voilà button, but I still get the wrong rendering of the notebook (see picture). Any more suggestion? 
Thanks!

<img width="1395" alt="Screen Shot 2020-06-03 at 7 43 30 PM" src="https://user-images.githubusercontent.com/13563701/83670291-39863280-a5d3-11ea-94f7-66a801f071f6.png">

**Comment by sbonaretti** [comment]
Hi @danielfrg,
Just wondering if you had time to reply to my last question. 
Thanks a lot! :)

**Comment by danielfrg** [comment]
Ah yes, looks like now you need to set `jupyter_config.json` instead, look at the example on this repo: https://github.com/danielfrg/jupyter-flex/blob/master/jupyter_config.json

**Comment by sbonaretti** [comment]
Thanks @danielfrg! It works! :)
